### ISSUE TITLE
Update handel and swagger template files

### ISSUE THREAD

**Issue by SpencerTuft** [byu-oit/generator-swagger-node-byu-api#3]
I was working with @byujol on helping others to migrate to servers that run NodeJS in a multi-container docker box. _If the whole team is wanting to work in multi-docker containers_, then we can update the handel template files to conform to that standard.

Another update that should be made is fixing the tags the swagger.json so that, when we upload the swagger.json to wso2, the endpoints are sorted into sections that correctly represent their functionality.

**Comment by mhailstone** [comment]
After discussing with @SpencerTuft we decided to actually remove tags for now because we don't have a defined reason for using tags and the sub-resources are a natural grouping for paths in the Swagger UI in WSO2 and other tools.

**Comment by SpencerTuft** [comment]
We also decided that the handel files in a project can be generated using the [github-bot](https://github.com/byu-oit/github-bot) instead of including them in the swagger-node-byu-api generator.
